# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build release

on:
  push:
    branches: ['master']

env:
  GITHUB_BUILD: true

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dev tools
        run: sudo apt-get install -y curl tree

      - name: Install luvit
        run: curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

      - name: Install dependencies
        run: ./lit install

      - name: Build bot
        run: ./luvit build.lua

      - name: Push LunaticSea build to artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'lunatic-sea-linux-amd64'
          path: build/

  win-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install luvit
        shell: pwsh
        run: PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'; iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"

      - name: Install dependencies
        run: ./lit install

      - name: Build bot
        run: ./luvit build.lua

      - name: Push LunaticSea build to artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'lunatic-sea-win-amd64'
          path: build/

  publish:
    name: Upload to prerelease
    needs: [win-build, linux-build]
    runs-on: ubuntu-latest
    steps:
      - name: Install dev tools
        run: sudo apt-get install -y curl tree

      - uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R