# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build release

on:
  push:
    branches: ["master"]

env:
  GITHUB_BUILD: true
  NIGHTLY_REPO: https://github.com/LunaticSea/nightly
  REPO: https://github.com/LunaticSea/LunaticSea

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dev tools
        run: sudo apt-get install -y curl tree

      - name: Install luvit
        run: curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

      - name: Install dependencies
        run: ./luvit make install

      - name: Build bot
        run: ./luvit make

      - name: Push LunaticSea binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: "lunatic-sea-linux-amd64"
          path: build/

  win-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install luvit
        shell: pwsh
        run: PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'; iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"

      - name: Install dependencies
        run: ./luvit make install

      - name: Build bot
        run: ./luvit make

      - name: Push LunaticSea binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: "lunatic-sea-win-amd64"
          path: build/

  publish:
    name: Upload to prerelease
    needs: [win-build, linux-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      - name: Declare file variables
        shell: bash
        run: |
          echo "linux_file_name=lunatic-sea-linux-amd64-${{ env.branch }}-${{ env.sha_short }}.bin" >> "$GITHUB_ENV"
          echo "win_file_name=lunatic-sea-win-amd64-${{ env.branch }}-${{ env.sha_short }}.exe" >> "$GITHUB_ENV"

      - name: Print all env
        shell: bash
        run: echo $GITHUB_ENV

      - uses: actions/download-artifact@v4

      - name: Rename linux binaries
        run: mv ./lunatic-sea-linux-amd64/LunaticSea ./${{ env.linux_file_name }}

      - name: Rename win binaries
        run: mv ./lunatic-sea-win-amd64/LunaticSea.exe ./${{ env.win_file_name }}

      - name: Create release
        run: gh release create $NIGHTLY_TAG -R ${{ env.NIGHTLY_REPO }} --latest=true --notes "$RELEASE_NOTE"
        env:
          RELEASE_NOTE: This commit is from ${{ github.sha }} in ${{ env.REPO }}
          GH_TOKEN: ${{ secrets.PERSONAL }}
          NIGHTLY_TAG: ${{ env.sha_short }}

      - name: Upload linux binaries to release
        run: gh release upload $NIGHTLY_TAG ./${{ env.linux_file_name }} --clobber -R ${{ env.NIGHTLY_REPO }}
        env:
          GH_TOKEN: ${{ secrets.PERSONAL }}
          NIGHTLY_TAG: ${{ env.sha_short }}

      - name: Upload win binaries to release
        run: gh release upload $NIGHTLY_TAG ./${{ env.win_file_name }} --clobber -R ${{ env.NIGHTLY_REPO }}
        env:
          GH_TOKEN: ${{ secrets.PERSONAL }}
          NIGHTLY_TAG: ${{ env.sha_short }}
