# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build release

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dev tools
        run: sudo apt-get install -y curl

      - name: Install luvit
        run: curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

      - name: Install dependencies
        run: lit install

      - name: Build bot
        run: luvit build.lua

      - name: Push ByteBlaze build zip to artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'LunaticSea'
          path: build/